### ISSUE TITLE
Getting an exo with a shotgun throws errors

### ISSUE THREAD

**Issue by TheRealNin** [TheRealNin/NS2Combat#12]

**Comment by TheRealNin** [comment]
I think GL does as well. You really shouldn't be able to get an exo with a shotgun since you can't get out.

**Comment by GhoulofGSG9** [comment]
Maybe you should be able to get out?

**Comment by MysteriousMilk** [comment]
I like not being able to get out.  That prevents player A from buying player B an exo because they have unspent points (since combat focuses on the individual).  This is probably also why weapons cannot be dropped.

I think you should be able to get an exo if you have a shotgun or GL.  What I think should happen is, upon death, the player loses their exo (because its hardcapped, need to give other players a chance to play exo) but retain the other upgrades they've purchased (primary weapon, welder, armor/wpn upgrades, etc).

This is the approach I'm taking with Combat++.

EDIT: Just realized that Exosuit already takes into account the owner (duh) so I guess I see no downside to letting the player eject.

**Comment by TheRealNin** [comment]
Fixed by refactoring the weapon purchase code and allowing players to eject from their exos
